import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { useEffect } from 'react';
import Highcharts from 'highcharts';

export default function Home() {
  useEffect(() => {
    (async () => {
      const data = await (await fetch('http://localhost:3000/api/charts')).json();
      Highcharts.chart('container', {
        chart: {
          type: data.type
        },
        title: {
          text: data.title
        },
        xAxis: {
          categories: data.categories
        },
        yAxis: {
          title: {
            text: data.yAxis.title.text
          }
        },
        series: data.series
      });
    })();
  }, [])
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div id="container"></div>
      </main>
    </>
  )
}
