import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { useEffect } from 'react';
import Highcharts from 'highcharts';

export default function Home() {
  useEffect(() => {
    /* 第1引数には実行させたい副作用関数を記述*/
    console.log('副作用関数が実行されました！')
      const chart = Highcharts.chart('container', {
          chart: {
              type: 'bar'
          },
          title: {
              text: 'Fruit Consumption'
          },
          xAxis: {
              categories: ['Apples', 'Bananas', 'Oranges']
          },
          yAxis: {
              title: {
                  text: 'Fruit eaten'
              }
          },
          series: [{
              name: 'Jane',
              data: [1, 0, 4]
          }, {
              name: 'John',
              data: [5, 7, 3]
          }]
      });
  },[])
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div id="container"></div>
      </main>
    </>
  )
}
